In [60]:
# NumPy and Pandas Project

In [59]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\excel\excel1\Top_10k_Asia_Companies.csv")
df.head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50

In [65]:
df.tail()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
9995,BlueSky Industries Ltd.,Michael Russell,Retail,Public,Malaysia,Kuala Lumpur,1973,143212,64711,78501,18005,12.57,31.04,605787.87,35746.76
9996,BlueSky Technologies Ltd.,Jeremy Ramos,IT Services,Public,Taiwan,Taipei,1953,114900,52355,62545,5938,5.17,18.77,344766.17,38953.70
9997,Prime Retail Ltd.,Alyssa Parker,Retail,Public,Vietnam,Ho Chi Minh City,2015,199886,112345,87541,3665,1.83,7.99,652603.86,2765.76
9998,Summit Manufacturing Ltd.,Dwayne Mahoney,Banking,MNC,Indonesia,Jakarta,1965,70603,40451,30152,6011,8.51,6.25,234201.22,180507.12
9999,Apex Industries Ltd.,Lauren Johnson,IT Services,Startup,Japan,Tokyo,2004,116570,76732,39838,12185,10.45,11.84,509802.32,262348.16

## 📘 NumPy Section

In [2]:
#Q1. Import NumPy
import numpy as np

In [3]:
#Q2. Create Arrays
arr=np.array(df.select_dtypes(include='number').head(10))
arr

array([[1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
        1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
        5.62715200e+04],
       [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
        3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
        2.25509200e+04],
       [1.98100000e+03, 2.65050000e+04, 1.85420000e+04, 7.96300000e+03,
        1.88570000e+04, 7.11500000e+01, 3.48700000e+01, 1.26758651e+06,
        1.05042120e+05],
       [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
        1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
        5.03203200e+04],
       [1.94500000e+03, 2.08436000e+05, 1.08447000e+05, 9.99890000e+04,
        6.63100000e+03, 3.18000000e+00, 2.72400000e+01, 6.85138260e+05,
        9.78035000e+04],
       [1.93800000e+03, 5.36460000e+04, 3.31880000e+04, 2.04580000e+04,
        1.77670000e+04, 3.31200000e+01, 1.18800000e+01, 1.31892950e+05,
        1.07498280e+05],
       [1.94500000e+03, 1.27097000e+05, 7.23810000e+04, 5.47160000e+04,
        3.80200000e+03, 2.99000000e+00, 3.37800000e+01, 6.99846330e+05,
        3.79268600e+04],
       [1.98800000e+03, 2.17672000e+05, 1.06263000e+05, 1.11409000e+05,
        1.89000000e+03, 8.70000000e-01, 5.28000000e+00, 1.08238792e+06,
        4.80155200e+04],
       [1.99800000e+03, 6.26800000e+04, 3.41260000e+04, 2.85540000e+04,
        9.80000000e+03, 1.56300000e+01, 4.48500000e+01, 8.63090320e+05,
        8.44442600e+04],
       [1.93700000e+03, 1.17635000e+05, 6.05780000e+04, 5.70570000e+04,
        8.88800000e+03, 7.56000000e+00, 3.32900000e+01, 4.91066360e+05,
        4.94586000e+03]])

In [61]:
#Q3. Array Dimensions

arr.ndim

2

In [5]:
# Q4. Shape & Size

arr.shape, arr.size

((10, 9), 90)

In [6]:
# Q5. Reshape

arr.reshape(5,-1).shape

(5, 18)

In [7]:
#Q6. Indexing & Slicing

arr[:3,:3]

array([[  1968., 203961.,  99445.],
       [  1973., 285617., 173129.],
       [  1981.,  26505.,  18542.]])

In [8]:
#Q7. Boolean Indexing

arr[arr[:,0]>arr[:,0].mean()]

array([[1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
        1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
        5.62715200e+04],
       [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
        3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
        2.25509200e+04],
       [1.98100000e+03, 2.65050000e+04, 1.85420000e+04, 7.96300000e+03,
        1.88570000e+04, 7.11500000e+01, 3.48700000e+01, 1.26758651e+06,
        1.05042120e+05],
       [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
        1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
        5.03203200e+04],
       [1.98800000e+03, 2.17672000e+05, 1.06263000e+05, 1.11409000e+05,
        1.89000000e+03, 8.70000000e-01, 5.28000000e+00, 1.08238792e+06,
        4.80155200e+04],
       [1.99800000e+03, 6.26800000e+04, 3.41260000e+04, 2.85540000e+04,
        9.80000000e+03, 1.56300000e+01, 4.48500000e+01, 8.63090320e+05,
        8.44442600e+04]])

In [9]:
#Q8. Fancy Indexing

arr[[0,2,4],:3]

array([[  1968., 203961.,  99445.],
       [  1981.,  26505.,  18542.],
       [  1945., 208436., 108447.]])

In [62]:
#Q9. Arithmetic Operations

arr+10

array([[1.97800000e+03, 2.03971000e+05, 9.94550000e+04, 1.04526000e+05,
        1.05590000e+04, 1.51700000e+01, 5.18500000e+01, 8.14973000e+05,
        5.62815200e+04],
       [1.98300000e+03, 2.85627000e+05, 1.73139000e+05, 1.12498000e+05,
        3.33300000e+03, 1.11600000e+01, 4.56300000e+01, 8.48546720e+05,
        2.25609200e+04],
       [1.99100000e+03, 2.65150000e+04, 1.85520000e+04, 7.97300000e+03,
        1.88670000e+04, 8.11500000e+01, 4.48700000e+01, 1.26759651e+06,
        1.05052120e+05],
       [1.98600000e+03, 1.48874000e+05, 1.00602000e+05, 4.82820000e+04,
        1.74510000e+04, 2.17200000e+01, 1.85300000e+01, 7.21530130e+05,
        5.03303200e+04],
       [1.95500000e+03, 2.08446000e+05, 1.08457000e+05, 9.99990000e+04,
        6.64100000e+03, 1.31800000e+01, 3.72400000e+01, 6.85148260e+05,
        9.78135000e+04],
       [1.94800000e+03, 5.36560000e+04, 3.31980000e+04, 2.04680000e+04,
        1.77770000e+04, 4.31200000e+01, 2.18800000e+01, 1.31902950e+05,
        1.07508280e+05],
       [1.95500000e+03, 1.27107000e+05, 7.23910000e+04, 5.47260000e+04,
        3.81200000e+03, 1.29900000e+01, 4.37800000e+01, 6.99856330e+05,
        3.79368600e+04],
       [1.99800000e+03, 2.17682000e+05, 1.06273000e+05, 1.11419000e+05,
        1.90000000e+03, 1.08700000e+01, 1.52800000e+01, 1.08239792e+06,
        4.80255200e+04],
       [2.00800000e+03, 6.26900000e+04, 3.41360000e+04, 2.85640000e+04,
        9.81000000e+03, 2.56300000e+01, 5.48500000e+01, 8.63100320e+05,
        8.44542600e+04],
       [1.94700000e+03, 1.17645000e+05, 6.05880000e+04, 5.70670000e+04,
        8.89800000e+03, 1.75600000e+01, 4.32900000e+01, 4.91076360e+05,
        4.95586000e+03]])

In [67]:
#Q10. Statistical Functions

np.mean(arr),np.std(arr)

(np.float64(124934.44899999998), np.float64(251787.3248958511))

In [12]:
#Q11. Aggregate Functions

np.sum(arr),np.min(arr),np.max(arr)

(np.float64(11244100.409999998), np.float64(0.87), np.float64(1267586.51))

In [13]:
# Q12. Sorting

np.sort(arr[:,0])

array([1937., 1938., 1945., 1945., 1968., 1973., 1976., 1981., 1988.,
       1998.])

In [14]:
#Q13. Searching

np.where(arr[:,0]>np.mean(arr[:,0]))

(array([0, 1, 2, 3, 7, 8]),)

In [15]:
#Q14. Filtering

arr[arr[:,1]>np.median(arr[:,1])]

array([[1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
        1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
        5.62715200e+04],
       [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
        3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
        2.25509200e+04],
       [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
        1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
        5.03203200e+04],
       [1.94500000e+03, 2.08436000e+05, 1.08447000e+05, 9.99890000e+04,
        6.63100000e+03, 3.18000000e+00, 2.72400000e+01, 6.85138260e+05,
        9.78035000e+04],
       [1.98800000e+03, 2.17672000e+05, 1.06263000e+05, 1.11409000e+05,
        1.89000000e+03, 8.70000000e-01, 5.28000000e+00, 1.08238792e+06,
        4.80155200e+04]])

In [16]:
#Q15. Unique Values

np.unique(df['Country'])

array(['China', 'India', 'Indonesia', 'Japan', 'Malaysia', 'Singapore',
       'South Korea', 'Taiwan', 'Thailand', 'UAE', 'Vietnam'],
      dtype=object)

In [17]:
#Q16. Concatenate

np.concatenate((arr[:2],arr[2:4]))

array([[1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
        1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
        5.62715200e+04],
       [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
        3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
        2.25509200e+04],
       [1.98100000e+03, 2.65050000e+04, 1.85420000e+04, 7.96300000e+03,
        1.88570000e+04, 7.11500000e+01, 3.48700000e+01, 1.26758651e+06,
        1.05042120e+05],
       [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
        1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
        5.03203200e+04]])

In [18]:
#Q17. Split Arrays

np.array_split(arr,2)

[array([[1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
         1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
         5.62715200e+04],
        [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
         3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
         2.25509200e+04],
        [1.98100000e+03, 2.65050000e+04, 1.85420000e+04, 7.96300000e+03,
         1.88570000e+04, 7.11500000e+01, 3.48700000e+01, 1.26758651e+06,
         1.05042120e+05],
        [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
         1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
         5.03203200e+04],
        [1.94500000e+03, 2.08436000e+05, 1.08447000e+05, 9.99890000e+04,
         6.63100000e+03, 3.18000000e+00, 2.72400000e+01, 6.85138260e+05,
         9.78035000e+04]]),
 array([[1.93800000e+03, 5.36460000e+04, 3.31880000e+04, 2.04580000e+04,
         1.77670000e+04, 3.31200000e+01, 1.18800000e+01, 1.31892950e+05,
         1.07498280e+05],
        [1.94500000e+03, 1.27097000e+05, 7.23810000e+04, 5.47160000e+04,
         3.80200000e+03, 2.99000000e+00, 3.37800000e+01, 6.99846330e+05,
         3.79268600e+04],
        [1.98800000e+03, 2.17672000e+05, 1.06263000e+05, 1.11409000e+05,
         1.89000000e+03, 8.70000000e-01, 5.28000000e+00, 1.08238792e+06,
         4.80155200e+04],
        [1.99800000e+03, 6.26800000e+04, 3.41260000e+04, 2.85540000e+04,
         9.80000000e+03, 1.56300000e+01, 4.48500000e+01, 8.63090320e+05,
         8.44442600e+04],
        [1.93700000e+03, 1.17635000e+05, 6.05780000e+04, 5.70570000e+04,
         8.88800000e+03, 7.56000000e+00, 3.32900000e+01, 4.91066360e+05,
         4.94586000e+03]])]

In [19]:
#Q18. Stack Arrays

np.vstack((arr[:2],arr[:2]))

array([[1.9680000e+03, 2.0396100e+05, 9.9445000e+04, 1.0451600e+05,
        1.0549000e+04, 5.1700000e+00, 4.1850000e+01, 8.1496300e+05,
        5.6271520e+04],
       [1.9730000e+03, 2.8561700e+05, 1.7312900e+05, 1.1248800e+05,
        3.3230000e+03, 1.1600000e+00, 3.5630000e+01, 8.4853672e+05,
        2.2550920e+04],
       [1.9680000e+03, 2.0396100e+05, 9.9445000e+04, 1.0451600e+05,
        1.0549000e+04, 5.1700000e+00, 4.1850000e+01, 8.1496300e+05,
        5.6271520e+04],
       [1.9730000e+03, 2.8561700e+05, 1.7312900e+05, 1.1248800e+05,
        3.3230000e+03, 1.1600000e+00, 3.5630000e+01, 8.4853672e+05,
        2.2550920e+04]])

In [20]:
#Q19. Insert/Delete

np.delete(np.insert(arr,0,0,axis=0),1,axis=0)

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.97300000e+03, 2.85617000e+05, 1.73129000e+05, 1.12488000e+05,
        3.32300000e+03, 1.16000000e+00, 3.56300000e+01, 8.48536720e+05,
        2.25509200e+04],
       [1.98100000e+03, 2.65050000e+04, 1.85420000e+04, 7.96300000e+03,
        1.88570000e+04, 7.11500000e+01, 3.48700000e+01, 1.26758651e+06,
        1.05042120e+05],
       [1.97600000e+03, 1.48864000e+05, 1.00592000e+05, 4.82720000e+04,
        1.74410000e+04, 1.17200000e+01, 8.53000000e+00, 7.21520130e+05,
        5.03203200e+04],
       [1.94500000e+03, 2.08436000e+05, 1.08447000e+05, 9.99890000e+04,
        6.63100000e+03, 3.18000000e+00, 2.72400000e+01, 6.85138260e+05,
        9.78035000e+04],
       [1.93800000e+03, 5.36460000e+04, 3.31880000e+04, 2.04580000e+04,
        1.77670000e+04, 3.31200000e+01, 1.18800000e+01, 1.31892950e+05,
        1.07498280e+05],
       [1.94500000e+03, 1.27097000e+05, 7.23810000e+04, 5.47160000e+04,
        3.80200000e+03, 2.99000000e+00, 3.37800000e+01, 6.99846330e+05,
        3.79268600e+04],
       [1.98800000e+03, 2.17672000e+05, 1.06263000e+05, 1.11409000e+05,
        1.89000000e+03, 8.70000000e-01, 5.28000000e+00, 1.08238792e+06,
        4.80155200e+04],
       [1.99800000e+03, 6.26800000e+04, 3.41260000e+04, 2.85540000e+04,
        9.80000000e+03, 1.56300000e+01, 4.48500000e+01, 8.63090320e+05,
        8.44442600e+04],
       [1.93700000e+03, 1.17635000e+05, 6.05780000e+04, 5.70570000e+04,
        8.88800000e+03, 7.56000000e+00, 3.32900000e+01, 4.91066360e+05,
        4.94586000e+03]])

In [21]:
#Q20. Flatten

arr.flatten()

array([1.96800000e+03, 2.03961000e+05, 9.94450000e+04, 1.04516000e+05,
       1.05490000e+04, 5.17000000e+00, 4.18500000e+01, 8.14963000e+05,
       5.62715200e+04, 1.97300000e+03, 2.85617000e+05, 1.73129000e+05,
       1.12488000e+05, 3.32300000e+03, 1.16000000e+00, 3.56300000e+01,
       8.48536720e+05, 2.25509200e+04, 1.98100000e+03, 2.65050000e+04,
       1.85420000e+04, 7.96300000e+03, 1.88570000e+04, 7.11500000e+01,
       3.48700000e+01, 1.26758651e+06, 1.05042120e+05, 1.97600000e+03,
       1.48864000e+05, 1.00592000e+05, 4.82720000e+04, 1.74410000e+04,
       1.17200000e+01, 8.53000000e+00, 7.21520130e+05, 5.03203200e+04,
       1.94500000e+03, 2.08436000e+05, 1.08447000e+05, 9.99890000e+04,
       6.63100000e+03, 3.18000000e+00, 2.72400000e+01, 6.85138260e+05,
       9.78035000e+04, 1.93800000e+03, 5.36460000e+04, 3.31880000e+04,
       2.04580000e+04, 1.77670000e+04, 3.31200000e+01, 1.18800000e+01,
       1.31892950e+05, 1.07498280e+05, 1.94500000e+03, 1.27097000e+05,
       7.23810000e+04, 5.47160000e+04, 3.80200000e+03, 2.99000000e+00,
       3.37800000e+01, 6.99846330e+05, 3.79268600e+04, 1.98800000e+03,
       2.17672000e+05, 1.06263000e+05, 1.11409000e+05, 1.89000000e+03,
       8.70000000e-01, 5.28000000e+00, 1.08238792e+06, 4.80155200e+04,
       1.99800000e+03, 6.26800000e+04, 3.41260000e+04, 2.85540000e+04,
       9.80000000e+03, 1.56300000e+01, 4.48500000e+01, 8.63090320e+05,
       8.44442600e+04, 1.93700000e+03, 1.17635000e+05, 6.05780000e+04,
       5.70570000e+04, 8.88800000e+03, 7.56000000e+00, 3.32900000e+01,
       4.91066360e+05, 4.94586000e+03])

In [22]:
#Q21. Transpose

arr.T

array([[1.96800000e+03, 1.97300000e+03, 1.98100000e+03, 1.97600000e+03,
        1.94500000e+03, 1.93800000e+03, 1.94500000e+03, 1.98800000e+03,
        1.99800000e+03, 1.93700000e+03],
       [2.03961000e+05, 2.85617000e+05, 2.65050000e+04, 1.48864000e+05,
        2.08436000e+05, 5.36460000e+04, 1.27097000e+05, 2.17672000e+05,
        6.26800000e+04, 1.17635000e+05],
       [9.94450000e+04, 1.73129000e+05, 1.85420000e+04, 1.00592000e+05,
        1.08447000e+05, 3.31880000e+04, 7.23810000e+04, 1.06263000e+05,
        3.41260000e+04, 6.05780000e+04],
       [1.04516000e+05, 1.12488000e+05, 7.96300000e+03, 4.82720000e+04,
        9.99890000e+04, 2.04580000e+04, 5.47160000e+04, 1.11409000e+05,
        2.85540000e+04, 5.70570000e+04],
       [1.05490000e+04, 3.32300000e+03, 1.88570000e+04, 1.74410000e+04,
        6.63100000e+03, 1.77670000e+04, 3.80200000e+03, 1.89000000e+03,
        9.80000000e+03, 8.88800000e+03],
       [5.17000000e+00, 1.16000000e+00, 7.11500000e+01, 1.17200000e+01,
        3.18000000e+00, 3.31200000e+01, 2.99000000e+00, 8.70000000e-01,
        1.56300000e+01, 7.56000000e+00],
       [4.18500000e+01, 3.56300000e+01, 3.48700000e+01, 8.53000000e+00,
        2.72400000e+01, 1.18800000e+01, 3.37800000e+01, 5.28000000e+00,
        4.48500000e+01, 3.32900000e+01],
       [8.14963000e+05, 8.48536720e+05, 1.26758651e+06, 7.21520130e+05,
        6.85138260e+05, 1.31892950e+05, 6.99846330e+05, 1.08238792e+06,
        8.63090320e+05, 4.91066360e+05],
       [5.62715200e+04, 2.25509200e+04, 1.05042120e+05, 5.03203200e+04,
        9.78035000e+04, 1.07498280e+05, 3.79268600e+04, 4.80155200e+04,
        8.44442600e+04, 4.94586000e+03]])

In [63]:
#Q22. Matrix Multiplication

a=arr[:5,:5]
arr.T

array([[1.96800000e+03, 1.97300000e+03, 1.98100000e+03, 1.97600000e+03,
        1.94500000e+03, 1.93800000e+03, 1.94500000e+03, 1.98800000e+03,
        1.99800000e+03, 1.93700000e+03],
       [2.03961000e+05, 2.85617000e+05, 2.65050000e+04, 1.48864000e+05,
        2.08436000e+05, 5.36460000e+04, 1.27097000e+05, 2.17672000e+05,
        6.26800000e+04, 1.17635000e+05],
       [9.94450000e+04, 1.73129000e+05, 1.85420000e+04, 1.00592000e+05,
        1.08447000e+05, 3.31880000e+04, 7.23810000e+04, 1.06263000e+05,
        3.41260000e+04, 6.05780000e+04],
       [1.04516000e+05, 1.12488000e+05, 7.96300000e+03, 4.82720000e+04,
        9.99890000e+04, 2.04580000e+04, 5.47160000e+04, 1.11409000e+05,
        2.85540000e+04, 5.70570000e+04],
       [1.05490000e+04, 3.32300000e+03, 1.88570000e+04, 1.74410000e+04,
        6.63100000e+03, 1.77670000e+04, 3.80200000e+03, 1.89000000e+03,
        9.80000000e+03, 8.88800000e+03],
       [5.17000000e+00, 1.16000000e+00, 7.11500000e+01, 1.17200000e+01,
        3.18000000e+00, 3.31200000e+01, 2.99000000e+00, 8.70000000e-01,
        1.56300000e+01, 7.56000000e+00],
       [4.18500000e+01, 3.56300000e+01, 3.48700000e+01, 8.53000000e+00,
        2.72400000e+01, 1.18800000e+01, 3.37800000e+01, 5.28000000e+00,
        4.48500000e+01, 3.32900000e+01],
       [8.14963000e+05, 8.48536720e+05, 1.26758651e+06, 7.21520130e+05,
        6.85138260e+05, 1.31892950e+05, 6.99846330e+05, 1.08238792e+06,
        8.63090320e+05, 4.91066360e+05],
       [5.62715200e+04, 2.25509200e+04, 1.05042120e+05, 5.03203200e+04,
        9.78035000e+04, 1.07498280e+05, 3.79268600e+04, 4.80155200e+04,
        8.44442600e+04, 4.94586000e+03]])

In [24]:
#Q23. Dot Product

np.dot(arr[0],arr[1])

np.float64(780062282325.271)

In [25]:
#Q24. Random Arrays
    
np.random.rand(3,3)

array([[0.06769768, 0.48604771, 0.15549692],
       [0.95294322, 0.1477033 , 0.68072417],
       [0.61617827, 0.72824803, 0.26809091]])

In [26]:
#Q25. Identity Matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#Q26. Diagonal Matrix

np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

## 📊 Pandas Section

In [ ]:
#Q1. Import Pandas

In [64]:
import pandas as pd
df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\excel\excel1\Top_10k_Asia_Companies.csv")
df

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BlueSky Industries Ltd.,Michael Russell,Retail,Public,Malaysia,Kuala Lumpur,1973,143212,64711,78501,18005,12.57,31.04,605787.87,35746.76
9996,BlueSky Technologies Ltd.,Jeremy Ramos,IT Services,Public,Taiwan,Taipei,1953,114900,52355,62545,5938,5.17,18.77,344766.17,38953.70
9997,Prime Retail Ltd.,Alyssa Parker,Retail,Public,Vietnam,Ho Chi Minh City,2015,199886,112345,87541,3665,1.83,7.99,652603.86,2765.76
9998,Summit Manufacturing Ltd.,Dwayne Mahoney,Banking,MNC,Indonesia,Jakarta,1965,70603,40451,30152,6011,8.51,6.25,234201.22,180507.12
9999,Apex Industries Ltd.,Lauren Johnson,IT Services,Startup,Japan,Tokyo,2004,116570,76732,39838,12185,10.45,11.84,509802.32,262348.16

In [34]:
#Q2. Load CSV

df.head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50

In [35]:
#Q3. Display Data

df

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BlueSky Industries Ltd.,Michael Russell,Retail,Public,Malaysia,Kuala Lumpur,1973,143212,64711,78501,18005,12.57,31.04,605787.87,35746.76
9996,BlueSky Technologies Ltd.,Jeremy Ramos,IT Services,Public,Taiwan,Taipei,1953,114900,52355,62545,5938,5.17,18.77,344766.17,38953.70
9997,Prime Retail Ltd.,Alyssa Parker,Retail,Public,Vietnam,Ho Chi Minh City,2015,199886,112345,87541,3665,1.83,7.99,652603.86,2765.76
9998,Summit Manufacturing Ltd.,Dwayne Mahoney,Banking,MNC,Indonesia,Jakarta,1965,70603,40451,30152,6011,8.51,6.25,234201.22,180507.12
9999,Apex Industries Ltd.,Lauren Johnson,IT Services,Startup,Japan,Tokyo,2004,116570,76732,39838,12185,10.45,11.84,509802.32,262348.16

In [36]:
#Q4. Shape

df.shape

(10000, 15)

In [37]:
#Q5. Columns

df.columns

Index(['Company_Name', 'CEO_Name', 'Industry', 'Company_Sector', 'Country',
       'City', 'Founded_Year', 'Employee_Count', 'Male_Employees',
       'Female_Employees', 'Last_Year_Hirings', 'Hiring_Rate (%)',
       'Average_Salary_LPA', 'Annual_Revenue_INR_Crores',
       'Company_Shares_INR'],
      dtype='object')

In [38]:
#Q6. Data Types

df.dtypes

Company_Name                  object
CEO_Name                      object
Industry                      object
Company_Sector                object
Country                       object
City                          object
Founded_Year                   int64
Employee_Count                 int64
Male_Employees                 int64
Female_Employees               int64
Last_Year_Hirings              int64
Hiring_Rate (%)              float64
Average_Salary_LPA           float64
Annual_Revenue_INR_Crores    float64
Company_Shares_INR           float64
dtype: object

In [39]:
#Q7. Describe

df.describe()

,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,1.000000e+04,10000.000000
mean,1986.323900,99929.825600,57501.170800,42428.654800,9989.61090,10.055387,21.470354,3.415403e+05,178677.083688
std,20.937436,57416.531148,34118.641431,25748.672765,8770.95878,5.813110,10.784202,1.999414e+05,132613.034142
min,1937.000000,105.000000,65.000000,40.000000,10.00000,0.010000,3.000000,1.771600e+02,237.360000
25%,1969.000000,50120.000000,28499.000000,20647.750000,2696.25000,5.050000,12.050000,1.688625e+05,52238.550000
50%,1986.000000,100219.500000,56498.500000,41387.000000,7544.00000,10.120000,21.490000,3.405491e+05,160158.660000
75%,2004.000000,149345.500000,84120.500000,61376.000000,15415.00000,14.990000,30.920000,5.153212e+05,294682.440000
max,2022.000000,285617.000000,173129.000000,112488.000000,39478.00000,71.150000,44.850000,1.267587e+06,429987.100000

In [40]:
#Q8. Info

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company_Name               10000 non-null  object
 1   CEO_Name                   10000 non-null  object
 2   Industry                   10000 non-null  object
 3   Company_Sector             10000 non-null  object
 4   Country                    10000 non-null  object
 5   City                       10000 non-null  object
 6   Founded_Year               10000 non-null  int64
 7   Employee_Count             10000 non-null  int64
 8   Male_Employees             10000 non-null  int64
 9   Female_Employees           10000 non-null  int64
 10  Last_Year_Hirings          10000 non-null  int64
 11  Hiring_Rate (%)            10000 non-null  float64
 12  Average_Salary_LPA         10000 non-null  float64
 13  Annual_Revenue_INR_Crores  10000 non-null  float64
 14  Company_Shares_INR         10000 non-null  float64
dtypes: float64(4), int64(5), object(6)
memory usage: 1.1+ MB

In [41]:
#Q9. Missing Values

df.isnull().sum()

Company_Name                 0
CEO_Name                     0
Industry                     0
Company_Sector               0
Country                      0
City                         0
Founded_Year                 0
Employee_Count               0
Male_Employees               0
Female_Employees             0
Last_Year_Hirings            0
Hiring_Rate (%)              0
Average_Salary_LPA           0
Annual_Revenue_INR_Crores    0
Company_Shares_INR           0
dtype: int64

In [42]:
#Q10. Drop Missing Values

df.dropna().shape

(10000, 15)

In [43]:
#"Replace or fill all missing values (NaN) in the DataFrame with 0."

df.fillna(0).head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50

In [44]:
#Q12. Rename Columns

df.rename(columns={'Company_Name':'Company'})

,Company,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,BlueSky Industries Ltd.,Michael Russell,Retail,Public,Malaysia,Kuala Lumpur,1973,143212,64711,78501,18005,12.57,31.04,605787.87,35746.76
9996,BlueSky Technologies Ltd.,Jeremy Ramos,IT Services,Public,Taiwan,Taipei,1953,114900,52355,62545,5938,5.17,18.77,344766.17,38953.70
9997,Prime Retail Ltd.,Alyssa Parker,Retail,Public,Vietnam,Ho Chi Minh City,2015,199886,112345,87541,3665,1.83,7.99,652603.86,2765.76
9998,Summit Manufacturing Ltd.,Dwayne Mahoney,Banking,MNC,Indonesia,Jakarta,1965,70603,40451,30152,6011,8.51,6.25,234201.22,180507.12
9999,Apex Industries Ltd.,Lauren Johnson,IT Services,Startup,Japan,Tokyo,2004,116570,76732,39838,12185,10.45,11.84,509802.32,262348.16

In [45]:
#Q13. Add New Column

df.assign(Total_Employees=df['Male_Employees']+df['Female_Employees']).head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR,Total_Employees
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52,203961
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92,285617
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12,26505
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32,148864
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50,208436

In [46]:
# Q14. Delete Column

df.drop(columns=['Hiring_Rate (%)']).head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,27.24,685138.26,97803.50

In [47]:
#Q15. Filtering
    
df[df['Country']=='India'].head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50

In [48]:
#Q16. Multiple Conditions

df[(df['Country']=='India') & (df['Employee_Count']>5000)].head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
3,HCLTech,C Vijayakumar,IT Services,Public,India,Noida,1976,148864,100592,48272,17441,11.72,8.53,721520.13,50320.32
4,Wipro,Srinivas Pallia,IT Services,Public,India,Bengaluru,1945,208436,108447,99989,6631,3.18,27.24,685138.26,97803.50

In [49]:
#Q17. Sorting


df.sort_values('Annual_Revenue_INR_Crores',ascending=False).head()

,Company_Name,CEO_Name,Industry,Company_Sector,Country,City,Founded_Year,Employee_Count,Male_Employees,Female_Employees,Last_Year_Hirings,Hiring_Rate (%),Average_Salary_LPA,Annual_Revenue_INR_Crores,Company_Shares_INR
2,Infosys,Salil Parekh,IT Services,Public,India,Bengaluru,1981,26505,18542,7963,18857,71.15,34.87,1267586.51,105042.12
7,Adani Enterprises,Gautam Adani,Infrastructure,Public,India,Ahmedabad,1988,217672,106263,111409,1890,0.87,5.28,1082387.92,48015.52
8,Tencent Holdings,Pony Ma,Technology,Public,China,Shenzhen,1998,62680,34126,28554,9800,15.63,44.85,863090.32,84444.26
1,Reliance Industries,Mukesh Ambani,Conglomerate,Public,India,Mumbai,1973,285617,173129,112488,3323,1.16,35.63,848536.72,22550.92
0,Tata Consultancy Services,K Krithivasan,IT Services,Public,India,Mumbai,1968,203961,99445,104516,10549,5.17,41.85,814963.00,56271.52

In [50]:
#Q18. GroupBy

df.groupby('Industry').size()

Industry
Automobile           2
Banking           1238
Conglomerate         1
Energy            1256
Engineering          1
Healthcare        1243
IT Services       1236
Infrastructure       1
Logistics         1251
Manufacturing     1309
Retail            1236
Technology           1
Telecom           1225
dtype: int64

In [51]:
#Q19. Aggregation

df.groupby('Country')['Annual_Revenue_INR_Crores'].agg(['mean','sum'])

                      mean           sum
Country
China        348700.995281  3.532341e+08
India        781483.977500  6.251872e+06
Indonesia    342578.783375  3.288756e+08
Japan        338202.309388  3.537596e+08
Malaysia     331743.127763  3.217908e+08
Singapore    340230.302174  3.473751e+08
South Korea  344671.970937  3.346765e+08
Taiwan       336108.194459  3.354360e+08
Thailand     342023.860380  3.327892e+08
UAE          346758.501159  3.530002e+08
Vietnam      340718.074344  3.482139e+08

In [52]:
#Q20. Value Counts

df['Country'].value_counts()

Country
Japan          1046
Vietnam        1022
Singapore      1021
UAE            1018
China          1013
Taiwan          998
Thailand        973
South Korea     971
Malaysia        970
Indonesia       960
India             8
Name: count, dtype: int64

In [53]:
#Q21. Unique Values

df['Industry'].unique()

array(['IT Services', 'Conglomerate', 'Engineering', 'Automobile',
       'Infrastructure', 'Technology', 'Healthcare', 'Telecom', 'Retail',
       'Logistics', 'Manufacturing', 'Energy', 'Banking'], dtype=object)

In [54]:
#Q22. Duplicates

df.duplicated().sum()

np.int64(0)

In [55]:
#Q23. Drop Duplicates

df.drop_duplicates().shape

(10000, 15)

In [56]:
#Q24. Merge DataFrames

left=df[['Company_Name','Country']].head();right=df[['Company_Name','Industry']].head();pd.merge(left,right,on='Company_Name')

                Company_Name Country      Industry
0  Tata Consultancy Services   India   IT Services
1        Reliance Industries   India  Conglomerate
2                    Infosys   India   IT Services
3                    HCLTech   India   IT Services
4                      Wipro   India   IT Services

In [57]:
#Q25. Join DataFrames

left.set_index('Company_Name').join(right.set_index('Company_Name'))

                          Country      Industry
Company_Name
Tata Consultancy Services   India   IT Services
Reliance Industries         India  Conglomerate
Infosys                     India   IT Services
HCLTech                     India   IT Services
Wipro                       India   IT Services

In [58]:
#Q26. Pivot Table

pd.pivot_table(df,index='Country',values='Annual_Revenue_INR_Crores',aggfunc='mean')

             Annual_Revenue_INR_Crores
Country
China                    348700.995281
India                    781483.977500
Indonesia                342578.783375
Japan                    338202.309388
Malaysia                 331743.127763
Singapore                340230.302174
South Korea              344671.970937
Taiwan                   336108.194459
Thailand                 342023.860380
UAE                      346758.501159
Vietnam                  340718.074344